### ISSUE TITLE
[meta] remove duplicate crate versions

### ISSUE THREAD

**Issue by metajack** [libra/libra#1050]
We currently have 49 duplicate crate versions in Libra Core. This meta bug documents them and tracks progress eliminating them.

To get a full list you can run `cargo lockfile dups`.

## Duplicate Crate Versions

- [ ] scopeguard (0.3.3, 1.0.0)
- [ ] crypto-mac (0.5.2, 0.7.0)
- [ ] percent-encoding (1.0.1, 2.1.0)
- [ ] structopt-derive (0.2.18, 0.3.2)
- [ ] url (1.7.2, 2.1.0)
- [ ] owning_ref (0.3.3, 0.4.0)
- [ ] hmac (0.5.0, 0.7.1)
- [ ] itertools (0.7.11, 0.8.0)
- [ ] byte-tools (0.2.0, 0.3.1)
- [ ] parking_lot_core (0.2.14, 0.3.1, 0.4.0)
- [ ] subtle (1.0.0, 2.1.1)
- [ ] curve25519-dalek (1.2.3, 1.2.3)
- [ ] arc-swap (0.3.11, 0.4.2)
- [ ] structopt (0.2.18, 0.3.2)
- [ ] strsim (0.8.0, 0.9.2)
- [ ] idna (0.1.5, 0.2.0)
- [ ] x25519-dalek (0.5.2, 0.5.2)
- [ ] nix (0.13.1, 0.14.1)
- [ ] protoc-grpcio (0.3.1, 1.0.2)
- [ ] wincolor (0.1.6, 1.0.2)
- [ ] ed25519-dalek (1.0.0-pre.1, 1.0.0-pre.1)
- [ ] proc-macro2 (0.4.30, 1.0.2)
- [ ] winapi (0.2.8, 0.3.8)
- [ ] siphasher (0.2.3, 0.3.0)
- [ ] grpcio-compiler (0.4.3, 0.5.0-alpha.2)
- [ ] termcolor (0.3.6, 1.0.5)
- [ ] rand_hc (0.1.0, 0.2.0)
- [ ] bit-vec (0.5.1, 0.6.1)
- [ ] block-buffer (0.3.3, 0.7.3)
- [ ] rand_core (0.3.1, 0.4.2, 0.5.1)
- [ ] quote (0.6.13, 1.0.2)
- [ ] parking_lot (0.4.8, 0.6.4, 0.7.1)
- [ ] miow (0.2.1, 0.3.3)
- [ ] quick-error (0.1.4, 1.2.2)
- [ ] term (0.4.6, 0.5.2)
- [ ] digest (0.7.6, 0.8.1)
- [ ] rand (0.3.23, 0.4.6, 0.5.6, 0.6.5, 0.7.0)
- [ ] syn (0.15.44, 1.0.5)
- [ ] base64 (0.9.3, 0.10.1)
- [ ] unicode-xid (0.1.0, 0.2.0)
- [ ] rand_chacha (0.1.1, 0.2.1)
- [ ] sha2 (0.7.1, 0.8.0)
- [ ] generic-array (0.9.0, 0.12.3)

**Comment by metajack** [comment]
The old scopeguard seems to come in via yamux and tokio-reactor. Tokio issue is tokio-rs/tokio#1348. yamux needs a dependency update.

**Comment by metajack** [comment]
sha2 0.7.1 comes via rusoto, which needs a dependency upgrade.

**Comment by metajack** [comment]
rusoto/rusoto#1510 submitted upstream to fix sha2 dupe.

**Comment by huitseeker** [comment]
One count of rand 0.4.x probably comes from `crypto/crypto`'s import of `zkcrypto/pairing`, upstream issue https://github.com/zkcrypto/pairing/issues/105

**Comment by huitseeker** [comment]
The (curve|x|ed25519)-dalek disjunction comes from us: client uses the upstream repo, crypto uses this series of forks:
https://github.com/calibra/ed25519-dalek
https://github.com/calibra/x25519-dalek
https://github.com/calibra/curve25519-dalek
This is a temporary situation necessary to help us offer the option of a formalized crypto backend for those, work is ongoing to no longer need those forks in the first place.

**Comment by metajack** [comment]
@huitseeker Thanks for those. I've updated the issue. Is there a tracking issue for unforking?

**Comment by metajack** [comment]
Updated the list and removed all the fixed ones. 36 dupes now.

**Comment by metajack** [comment]
Updated the list and removed fixed. 54 dupes now.
