### ISSUE TITLE
[language] Path towards reading consensus info in Move

### ISSUE THREAD

**Issue by runtian-zhou** [libra/libra#1083]
## Motivation

Currently the Move VM is totally ignorant of the consensus info. That is to say, the Move code will not be able to know informations about the current block proposed by the leader, e.g: current leader address, number of votes each of the validators get when being elected, current block time, etc. These will be critical information that the system contracts might need for on-chain governance. This is also important for third party modules as it will provide them a consensus approved wall clock time, which could be used to implement things like hashed time locks.

## Pitch

Let's say we want to persist following struct that comes from consensus:
``` rust
struct BlockMetadata {
  id: HashValue,
  timestamp_usec: u64,
  previous_block_votes: HashMap<AccountAddress, Signature>,
  proposer: AccountAddress,
}
```
At the end of a block, executor would forward such struct to the MoveVM. MoveVM is responsible for creating a special transaction that would update a special resource on chain that encodes the consensus info called `BlockMetadata` and emit a system event to indicate that a new block is indeed being proposed. This resource should be read-only in the regular user transactions. The special transaction should look something like this:
``` rust
// pseudo code
import 0xA.LibraTime
import 0xB.LibraConsensus
main (timestamp: u64, votes: Vector.T<address, signature>, proposer: address) {
    LibraTime.set_time(move(timestamp));
    LibraConsensus.add_votes(move(votes));
    LibraConsensus.add_proposer(move(proposer));
    emit_event(..., NewBlock{...});
}
```
Note that the `BTreeMap` gets converted into a vector when it was passed to Move. The reason is we don't have a good implementation of maps in Move yet.

Such transaction should have exact once semantics and is generated **independently** across validators so that we would know all good nodes did encode the consensus info correctly just by looking at the executed state hash.

## Implementation plan:

- [x] Implement a rust struct to represent the consensus info that the VM would use to execute the special transaction. #1068
- [x] Change the MoveVM api to be following:
``` rust
pub trait VMExecutor {
    /// Executes a block of transactions and returns output for each one of them.
    fn execute_block(
        transactions: Vec<Transaction>,
        config: &VMConfig,
        state_view: &dyn StateView,
    ) -> Vec<TransactionOutput>;
}
```
See #1173 for the discussion.

- [x] Implement a module to hold such resource on-chain that is only readable for user transactions with a private function to update it. #1489 
- [x] Implement the VM logic so that the MoveVM can forward the struct to the module written in step 3.  #1611 

And we are done! By then we should be able to read trust-worthy consensus info on chain!

**Comment by sblackshear** [comment]
> main (timestamp: u64, votes: Vector.T<address, signature>, proposer: address) {

The question of how to represent `votes` here is an interesting one. At least in the current plan, only consensus needs to read this info (no modules), and only via an event. So we might just want to pass in votes as a `bytearray` + emit that `bytearray` directly. Otherwise we'll do a Rust encoding -> Move encoding -> event bytes encoding -> Rust encoding roundtrip that we don't need to do...

This will also let us avoid taking `Vector`s as input to transaction scripts (which is currently not supported + controversial to support).
