### ISSUE TITLE
[netcore] Encode full protocol stack in multiaddr when dialing

### ISSUE THREAD

**Issue by phlip9** [libra/libra#1158]
# 🚀 Feature Request

The existing transports only dial the TCP/IP stack and negotiate the rest of the protocols over-the-wire after connecting. In other words, all advertised addresses are of the form: `"/ip4/1.2.3.4/tcp/1234"` or `"/ip6/::1/tcp/3333"` and subsequent protocols like Noise or yamux are negotiated interactively using the `"/libra/protocol-interactive"` protocol.

One issue is that all the information needed to securely dial a peer is not included in the protocol stack. For example, discovery PeerInfo's for Full Nodes will need to include a Noise static pubkey in addition to the `"/ip4/1.2.3.4/tcp/1234"` addr.

Instead of tightly coupling Noise to the dialing process, we can have peers advertise the full protocol stack for how to dial them. Such a multiaddr might look like: `"/ip4/1.2.3.4/tcp/1234/noise_ix_25519_aesgcm_sha256/1.0.0/<noise_pubkey>/yamux/1.0.0"`. Advertising a full protocol stack has the advantage of revealing the listener's Noise pubkey to the transport at creation time, which allows us to use a Noise IK handshake vs the current Noise IX handshake. (cc @mimoo)

This change would also allow cleaner design of VFN `PeerInfo`'s, i.e., from this:

```protobuf
// A `PeerInfo` represents the network address(es) of a Peer.
message PeerInfo {
  // Monotonically increasing sequence number used to allow peers to issue
  // updates to their `PeerInfo` and prevent attackers from propagating old
  // `PeerInfo`s. This is usually a timestamp.
  uint64 seqnum = 1;
  // Network static public key for Noise secure handshake.
  bytes pubkey = 2;
  // How a clients and other nodes should dial this peer. An address is a serialized 
  // [multiaddr](https://multiformats.io/multiaddr/).
  repeated bytes addrs = 3;
}
```

to just this, where the multiaddr field encapsulates all information needed to dial the peer:

```protobuf
// A `PeerInfo` represents the network address(es) of a Peer.
message PeerInfo {
  // Monotonically increasing sequence number used to allow peers to issue
  // updates to their `PeerInfo` and prevent attackers from propagating old
  // `PeerInfo`s. This is usually a timestamp.
  uint64 seqnum = 1;
  // How a clients and other nodes should dial this peer. An address is a serialized 
  // [multiaddr](https://multiformats.io/multiaddr/).
  repeated bytes addrs = 2;
}
```

This change would also allow us to dial peers with an optimal number of round-trips, as the peer advertises the specific protocol it supports at the endpoint, so we don't need interactive negotiation. Currently we need two additional, full round-trips for interactively negotiating "/noise_ix" and "/yamux" after establishing a connection.

Note: applying this same change to Validator discovery might prove challenging, as the Noise static pubkey is somewhat dynamic (effectively a pubkey stored on-chain in the validator set). One possibility might be removing the `network_identity_public_key` from the validator set and only using the `network_signing_key` to authenticate a multiaddr that contains the Noise static pubkey.

EDIT (2019/10/18): An additional benefit is that we can circumvent any cryptographic protocol downgrading attacks in one fell swoop. To see why this is true, consider that we currently negotiate our cryptographic protocol (Noise) interactively and in-the-clear when opening/handling a new connection. An on-path attacker just has to substitute the Noise version to an old, vulnerable version to compromise the connection. By advertising the cryptographic protocol in the multiaddr itself, we conveniently pin the connection to that specific version (so long as the advertising process is secure). 

## Implementation Steps

- [ ] Add a generic transport that supports dialing several sub-transports. The transport should parse the full protocol stack, build a transport for that protocol stack, and delegate dialing to the newly built transport. Returns a `BoxedTransport<(Identity, impl StreamMultiplexer), impl ::std::error::Error>`.
- [ ] Add a listening transport that expects a specific protocol stack when listening on some port. This means a node can support different transport protocols by assigning each transport to a unique port.
- [ ] Fork `rust-libp2p/multiaddr` to add our protocols so the multiaddr protocol identifiers are compact, e.g., 1-2 bytes vs. `"noise_ix_25519_aesgcm_sha256"`.

cc @bothra90 @bmwill

**Comment by mimoo** [comment]
(I'm fully supporting using IK instead of IX for Noise)

**Comment by phlip9** [comment]
Closed by #3478
