### ISSUE TITLE
[types] Separate System transaction from SignedTransaction

### ISSUE THREAD

**Issue by runtian-zhou** [libra/libra#1173]
# 🚀 Feature Request

## Motivation

Currently `SignedTransaction` is the protocol that the user would use to send transaction to the AC/mempool and the full node would use for VM execution. This is not ideal because there would be a number of system level transactions that should only be emittable by the validator itself. (e.g: The WriteSet transaction that we use to encode genesis. And there will be reconfiguration transaction coming shortly.) With our current implementation, the user will be able to emit those special transactions to the system freely. Although it is easy to filter them out at AC level, we just can't afford messing such important logic up. Thus I would propose we should create a separate notion for `UserTransaction` and `SystemTransaction`, and have different type wrappers in Rust to guard against confusing them.

## Pitch

What it look like right now:

We have a single type of `SignedTransaction` with its payload to be three of the following:
``` rust
pub enum TransactionPayload {
    WriteSet(WriteSet),
    /// A transaction that publishes code.
    Module(Module),
    /// A transaction that executes code.
    Script(Script),
}
```

I will propose us to get rid of the `WriteSet` variant, which is supposed to be a system transaction. And add a enum as following:
``` rust
pub enum ExecutorTransaction {
    User(SignedTransaction),
    WriteSet(WriteSet),
    BlockPrologue(BlockMetaData),
}
```
This new `ExecutorTransaction` enum will be the api used internally in the libra node to represent the transaction to be processed and persisted. By doing that, users would no longer be able to publish those system transactions such as `WriteSet` to the network.

## RoadMap
- [x] Define such enum in types. #1175 
- [x] Implement a Canonical Serializer/De for the new struct. #1229 
- [x] Change the storage schema to store this new struct. #1229 
- [x] Change public/private write APIs to use this new struct in transaction. #1271 #1287 
- [x] Change public reading APIs to use the new struct.  #1405 
- [x] Change the VM interface to use this new struct. #1281 
- [ ] Modify executor code to use this new mechanism to submit genesis writeset.
- [ ] Get rid of the `WriteSet` variant in current `TransactionPayload`.
