### ISSUE TITLE
[Roadmap][Storage] Execution Refactoring

### ISSUE THREAD

**Issue by gc3** [libra/libra#1427]
This issue tracks the refactoring project towards `Execution` module. By definition, `Execution` should be stateless. This basically means any input to `Execution` will always produce the same output, just like `MoveVM`. It is worth noting that "stateless" doesn't put the lid on caching/storing any internal state for optimization purpose but the module itself must hide these states transparently to users and acts as it doesn't have any state.

This issue tracks the refactoring effort of `Execution` to make it stateless, including solving the following issues:
1. The execution itself maintains a block tree shares the exactly the same as that of the `Consensus`, with different metadata though. It is an unnecessary engineering overhead and will become a tech debt sooner or later as Execution module should not be aware of blocks' relationships. Moreover, according to TCB design, `Execution` and `Consensus` will belong to different trusted domain so it is reasonable to let `Consensus` solely manages `block_tree`.
2. The execution communicates with other modules such as `state_synchronizer` and `Consensus` through GRPC. Not only it's an unnecessary complexity but also it may be replaced by other networking utility tools if TCB requires it to be isolated for security concerns. For simplicity and perf, it is always preferable to remove boilerplate GRPC wrappers of execution API.
3. Besides these, execution module has a built-in working thread providing basic async functionalities. Again, this complication could be taken by the caller/user of it such as consensus since the async api mainly serves parallel computation for block tree. In fact, due to some reason, `Consensus` blocks on each async api call, which makes it not such useful. So we plan to get rid of async apis.
4. Beside `block_tree`, `Execution` caches some external data which should be handles by the caller at a higher level. This further exacerbates the `statefulness` problem because most API call mutates the data so methods cannot be idempotent.

- [x] dedup block tree #803 #898 #1026 #1052 #1097 #1359 
- [x] remove GRPC #939
- [x] convert async api to sync #1733 
- [x] make `Executor` completely stateless #1397 #1733
