### ISSUE TITLE
[Consensus] An ability to start with an empty consensusDB

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#2188]
Today Consensus can start without a consensus DB only if its ledger points to the end of an epoch (in this case Consensus generates a new genesis and starts a new epoch). Without a DB Consensus cannot start because it doesn't have a root for the tree.

This is unfortunate and might limit our troubleshooting abilities. There is no inherent limitation here: a node could try to retrieve some blocks from its peers instead of simply crash looping.

**Comment by ZhenjieRuan** [comment]
## Current Structure
`ChainedBFTSMR` is responsible for starting the whole consensus process. At start up it will try to gather startup data which includes the latest ledger info and the data from local consensus db. The data will be held in `InitialData: RecoveryData<T>`. Then it will construct event processor etc. and start processing events. `InitialData` will be used in the whole startup process.
Currently, the root block must be found when constructing the recovery data before everything is initialized. This is unnecessary as this information is not needed at a much later stage when constructing the block store. This is the major thing that's preventing us to start from an empty consensus db right now.
## Proposal
1. Break up the `RecoveryData` data structure into two pieces. The first piece will be used to spin up `EpochManager` and network functionality. The second piece will be constructed by `EventProcessorPrelude`(see item 2).
2. Split `EventProcessor` starting procedure into two parts. The first part will be `EventProcessorPrelude` which will construct necessary data for `EventProcessor` to start. If it can't construct recovery data from local consensus db, the prelude will wait for `sync_info_msg`, this way we can do a fast forward sync from the peer using the information contained in `sync_info`. When `EventProcessorPrelude` finished constructing the necessary data for `EventProcessor` it will hand the data back to the `EpochManager` and `EpochManager` will continue the startup flow.

@zekun000 @dmitri-perelman Please feel free to comment if there is any concern or unclarity

**Comment by ZhenjieRuan** [comment]
## TODOs
- [ ] Use startup sync processor in `chained_bft_smr`
- [ ] Unit test for startup sync processor
- [ ] Smoke test for testing start from empty consensus db
