### ISSUE TITLE
[Consensus] Score Based Leader Election

### ISSUE THREAD

**Issue by ZhenjieRuan** [libra/libra#2420]
## Motivation
Currently we use deterministic function based on size of validator set to determine who will be the leader of next round(for details please see `multi_proposer_election.rs` and `rotating_proposer_election`). This is undesirable in the case when a validator is down since whenever the node is elected leader it will be a timeout and we take a performance hit. We want to have a way of excluding downed node from leader election and a way of bring it back after it's alive again.

## TODOs
- [ ] Investigate what metadata we currently store on chain and if the data is enough to deduce the health state of a node
- [ ] A deterministic algorithm for leader scoring
- [ ] A way to bring back a node after the node is excluded(e.g. If a downed node voted again it's eligible to participate in leader election again)

**Comment by bothra90** [comment]
Can consensus leverage the `LostPeer` signal from networking layer about node availability? If 2/3rd nodes agree that a node is down/unreachable a fixed number of blocks before it's that node's turn to be leader, they should be able agree on another leader in advance. Currently node health information is not stored on chain though.

**Comment by ZhenjieRuan** [comment]
@bothra90 Can you tell me a bit more about the `LostPeer` signal? Right now each validator will be able to know the leader independently without network communication because the algorithm is deterministic and I would like to keep it that way. Just an early thought, we can probably know who is down by analyzing the chain since we have something like `BlockMetadata`, don't know if we have enough data stored in it to infer who is down though.
