### ISSUE TITLE
[network][discovery] support key + address rotation flow

### ISSUE THREAD

**Issue by phlip9** [libra/libra#2426]
### Overview

Validators need to be able to rotate their identity key (which authenticates the secure transport) and advertised addresses (how other validators can dial them).

### Related Issues

#2332, #2367, #1547 

### Work Items

- [x] rotate validator config transaction
- [ ] observe reconfiguration with new discovery set and our newly rotated discovery info
- [ ] notify network somehow that our discovery info changed (update config? needs persistence...)
- [ ] network supports listening on multiple local addresses (#1896)
- [ ] network supports changing config dynamically (including identity keys, listen addresses, etc)
- [ ] integrate with cli tooling to drive rotation process
