### ISSUE TITLE
[Roadmap][Move] Testing infrastructure enhancements

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#3777]
This issue tracks a set of enhancements that we would like to make to the testing infrastructure for the Move compiler and VM before launch.

- [x] ~~Automatic test generation: Update it to work with the new file format and possibly make some improvements as well~~
- [x] Functional test refactoring
- [x] Code coverage testing for Move
- [x] Proptests and fuzzing for the bytecode verifier and VM
- [x] ~~Proptests and fuzzing for the VM~~
- [x] ~~Testing with automatic transaction generation~~

**Comment by bob-wilson** [comment]
Move code coverage testing is supported as of #3805

**Comment by bob-wilson** [comment]
For tracking purposes, we're going to consolidate the work on proptests and fuzzing for the bytecode verifier and VM into a single item on the list here.

**Comment by bob-wilson** [comment]
At this point, we're not going to make more progress on either automatic test generation or automatic transaction generation for Libra v1. We'll continue working on those in the future, but I'm going to take them off the list here.

**Comment by bob-wilson** [comment]
We've got some nice improvements to the functional testing framework now and are not actively planning further changes in that area for v1.

**Comment by bob-wilson** [comment]
Ditto for VM proptests and fuzzing. There is always more we can do and will plan to do in the future, but we're at a good place for v1.
