### ISSUE TITLE
[Roadmap][Move] Compiler enhancements

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#3778]
This issue tracks a set of enhancements that we would like to make to the Move compiler before launch.

- [x] Constraints to avoid borrow checker iteration
- [x] Constants
- [x] Resolve open syntax questions
- [x] Support aliasing for functions, structs, and constants
- [x] Script blocks
- [x] New "signer" primitive type with move_to bytecode

**Comment by bob-wilson** [comment]
Script blocks were added in #3669

**Comment by bob-wilson** [comment]
Aliasing support was added in #3920 (except for constants, which we haven't yet implemented) and in #4139 for spec contexts

**Comment by bob-wilson** [comment]
Signer and move\_to support was added in #3919

**Comment by bob-wilson** [comment]
The two open syntax questions mentioned here have been resolved:

(1) Brackets for conditionals and loops: Should you be allowed to write "if (e) break" or "while (e) i = i + 1"? We will keep the current syntax where brackets around a single expression are optional. We generally prefer brackets except for conditionals on one line, but we can use a (future) auto-formatting tool to make that distinction.

(2) Semicolons after conditionals and loops (with brackets): Should you be required to write "if (e) { s }; x = x + 1"? We will keep the current syntax where semicolons between expressions in a sequence are mandatory. The consistency and clarity here is more important than compatibility with Rust and C-based languages.

**Comment by bob-wilson** [comment]
Compiler support for constants landed in #4653

**Comment by bob-wilson** [comment]
Constraints to avoid borrow checker iteration were enabled in #4853 (There is more work to do later to take advantage of this, but for now we will ensure that the necessary constraints are satisfied.)

This task is now complete.
