### ISSUE TITLE
[Roadmap][Move] Code cleanups

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#3779]
This issue tracks a set of code cleanups that we would like to make to the Move compiler, VM, and related components before launch.

- [x] Bytecode verifier
- [x] VM runtime
- [x] VM Libra layer
- [x] Genesis
- [x] Separate success/failure epilogues
- [x] Core modules
- [x] VM file format

**Comment by bob-wilson** [comment]
The primary cleanup for the bytecode verifier was done in #3633. There may be some other smaller changes still to come, but that was the main thing.

**Comment by bob-wilson** [comment]
A separate failure epilogue was implemented in #4302

**Comment by bob-wilson** [comment]
The VM file format is done now. The last (planned) change in that area was #4495

**Comment by bob-wilson** [comment]
We're not planning any further cleanups for genesis, so that part is done now.

**Comment by bob-wilson** [comment]
We are now done with cleanups in the VM runtime, Libra Adapter, and Libra Framework (aka Core Modules). This issue is now resolved.
