### ISSUE TITLE
[Roadmap][Move] Documentation

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#3781]
This issue tracks a set of documents that we would like to develop related to the Move compiler, VM, and related components before launch.

- [x] Specification of Libra/Move adapter, including VM runtime implementation
- [x] Events
- [x] ~~VM runtime implementation~~
- [x] Other documentation updates

Note that this issue does not include documentation for the Move source language, which is a larger effort that we will track separately.

**Comment by bob-wilson** [comment]
I'm removing the list item here for documenting multicurrency and compliance features. We're planning to do that along with adding specifications in the Move modules, so we don't need to track it separately here.

**Comment by bob-wilson** [comment]
We are going to consolidate the specification document with the VM runtime implementation document.

**Comment by bob-wilson** [comment]
We're still working a spec for the Libra/Move adapter and documentation for events, but we've finished writing docs on gas, accounts, and transaction types. I am marking the "Other documentation" task as complete.

**Comment by bob-wilson** [comment]
We have a draft document describing Events out for review (not yet published). Marking that item as complete.

**Comment by bob-wilson** [comment]
The Move Adapter (and VM) specification will continue to be developed over time, but we've got something in place for v1 now, so I'm going to close out this task.
