### ISSUE TITLE
[Roadmap][Move] Standard library and Libra Framework changes

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#3782]
This issue tracks a set of changes that we would like to make to the Move standard library before launch.

- [x] On-chain governance with capabilities
- [x] Scripts, etc. for Association operations
- [x] Core module and script updates for mainnet
- [x] New resource/module naming convention
- [x] Adopt signer/move_to in core modules and scripts

**Comment by bob-wilson** [comment]
The signer/move_to feature was adopted in #3819. We're continuing to clean up uses of the old Transaction::Sender and move_to_sender in a series of subsequent PRs.

**Comment by bob-wilson** [comment]
We have decided to defer implementing polymorphic event streams until a later release. I have removed that item from the list here.

**Comment by bob-wilson** [comment]
The new naming convention has been adopted now. The last change was #4535

**Comment by bob-wilson** [comment]
I am retitling this issue to reflect our latest thinking about the distinction between Libra-specific Move modules and standard modules that apply to any application of Move. We plan to refer to the former modules as the "Libra Framework".

**Comment by bob-wilson** [comment]
Support for on-chain governance with capabilities was substantially completed with role-based permissions in #4501, with some follow-up work in #4637

**Comment by bob-wilson** [comment]
We've made a number of changes to update the core modules and scripts to mainnet behavior, most recently the changes for minting (#4772, #4791). There might still be some small changes but that item is now substantially done.

**Comment by bob-wilson** [comment]
We're done with scripts to support operations for the Libra Assocation. That completes the planned work for this issue.

There are still some late-breaking changes going in, e.g., https://github.com/libra/libra/pull/4972. Hopefully that is the last one, but it's possible that there may be more due to things we don't know about yet. I'm going to go ahead and consider this issue done, since we've completed all the planned work here.
