### ISSUE TITLE
[Roadmap][Move] Testing

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#3785]
This issue tracks a set of testing tasks related to the Move compiler, VM, and related components that we would like to do before launch.

- [x] Audit existing tests for the standard library
- [x] Audit existing tests for the VM and bytecode verifier
- [x] Get to 100%-ish code coverage in VM TCB
- [x] Test versioning and upgrades
- [x] Figure out how to test to confirm that module updates are compatible

**Comment by bob-wilson** [comment]
@runtian-zhou has completed his plans for testing versioning and upgrades.

**Comment by bob-wilson** [comment]
The tests for the standard library are in pretty good shape now, with essentially 100% code coverage. Marking the audit task as complete....

**Comment by bob-wilson** [comment]
We added testing for module update compatibility in #5529

**Comment by bob-wilson** [comment]
There is always more that can be done when it comes to testing, but at this point, we're satisfied with the tests in place for the VM and bytecode verifier, and our code coverage (although not at 100%) is also in pretty good shape. We should definitely continue improving those areas in the future, but we can consider this task completed for v1.
