### ISSUE TITLE
[network] Hardening

### ISSUE THREAD

**Issue by davidiw** [libra/libra#3985]
# LibraNet

This issue details ur vision for the initial LibraNet and the series of work that remains to get us there.

LibraNet consists of a set of framework to establish connections with remote peers over TCP connections enabling bidirectional communication, i.e., requests can be sent in either direction.

## Networks

The Libra Network contains 3 types of networks:

* a private validator network
* public access to the validator network via a set of fullnodes (validator fullnode network)
* many, distinct private networks, including, for example, one or more fullnodes connected directly to the validator

public => VFN => validator
private_external => private_validator => validator

Only the validator network has the notion of equal peers and forms a mesh network. The rest of the networks have clear downstream and upstream network endpoints, eventually leading up to the validators. There are no connections between peers at the same level.

## Protocols and data flow

These networks will speak the following protocols:

* Consensus (validators only)
* State Synchronization - retrieving the current state of the network
* Mempool - submitting transaction
* HealthCheck

The data flow across these networks isn't necessarily bidirectional. Libra has a designation of downstream / upstream. Downstream peers retrieve blockchain updates from upstream peers. Downstream peers push transactions to upstream peers. The network generalizes into a tree structure with the validator network as its root. Each node from further out is downstream from the node closer to the validators. Specifically,

* validator networks act as equal peers in which each peer plays the role as both an upstream and downstream peer to each other
* one or more fullnodes, connect via a private network, directly to the validator, this is known as the validator fullnode network or VFN. In this arrangement, the validator is upstream to these fullnodes
* the VFN provides public access to libra. Peers connected to this network are downstream to the VFN.

## Discovery

Each of these networks employs different means for discovery:

* validator network leverage the ledger, specifically, the current ValidatorSet, to learn of other validators network addresses and public keys, this is known as onchain discovery.
* similarly a peer desiring to connect to the VFN can learn of all VFNs from the current ValidatorSet.
* private networks must be manually configured leveraging the SeedPeers within the NodeConfig

## Security

LibraNet leverages noise to provide authentication and encryption. In practice, only authentication is a requirement. 

The expectation for each network is:

* validator network employs bidirection authentication via the data onchain
* VFN do not authenticate to validators but do authenticate validators (i.e., unidirectional authentication)
* nodes connecting to the VFN authenticate the VFN via the data onchain but those nodes themselves are not authenticated (i.e., unidirectional authentication)
* private networks can leverage SeedPeers for upstream authentication and network peers for (optional) downstream authentication

## Legacy / Deprecated Notions

* Gossip is not intended for production usage.

# Tasks 

What follows are a list of features that need to be completed shortly for proper hardening of our network:

- [ ] Support multiple listen addresses, namely IPv4 and IPv6, for a single network, see https://github.com/libra/libra/issues/1896.
- [x] Enforce correct PeerId usage in code: https://github.com/libra/libra/issues/3960
- [x] Move advertised_address and discovery_interval_ms into the Variant for Gossip in NetworkConfig
- [x] Make NetworkIdentityKey support an enum that is either the key is in the config or in a secure store along with the name of the key in secure store
- [x] Fullnode networks should only ever have 3 active connections or at least be capped by the config
- [ ] Consider having a FullnodeNetworkConfig and ValidatorNetworkConfig that share the appropriate common bits but have additional fields that make sense for them
- [x] Add a network id to NetworkConfig and propagate it into networking for logging and metrics and potentially even the means to define upstream peer network. Network id should be exchanged during handshake and two different networks should never try to talk to each other.
- [x] Add a chain id to BaseConfig. This should propagate to Network and be exchanged during handshake. Two different chains should never try to talk to each other. See https://github.com/libra/libra/issues/4011
- [ ] Explore a means to properly load balance across nodes in a network. We could start first with each peer gets 1 / k * estimated bandwidth and then explore means to measure available bandwidth and to support dynamic distribution
- [x] Use StateSync reconfiguration in onchain discovery: https://github.com/libra/libra/issues/3925
- [x] Mempool within a fullnode should broadcast transactions to all upstream peers

**Comment by agclement** [comment]
> ## Networks
> The Libra Network contains 3 types of networks:
> 
> * a private validator network
> * public access to the validator network via a set of fullnodes (validator fullnode network)
> * many, distinct private networks, including, for example, one or more fullnodes connected directly to the validator
> 

Would it make sense to reframe this as:
* **required** a private validator network
* **required** a public facing full node network (ring around the core validator network)
* **optional** many, distinct private full node networks connected to the public ring (externally operated)
* **optional** private full node networks connected directly to a validator (validator operated)

Motivation:
* the first two networks are the 'core' of the system that must be present and are collectively operated by the association members.
*  the third network is the one which non-association members can, in principle, instantiate.
*. the fourth network is a capability that association members are likely to leverage to better support their core systems.

**Comment by davidiw** [comment]
My knee-jerk reaction was that the private networks are the same. And maybe they are. Let's see...

VFN is public -> VFN -> validator
PrivateFN is maybe something -> private -> public -> VFN -> validator
or private -> VFN -> validator

So what do we gain if we have both of these as top level types? Maybe implicit upstream networks? But we already get that because validator is always upstream, so the VFN is kind of implicitly there already. Now with chains of pure private networks, we likely need to explicitly define upstream, sigh.

Also not really optional, we need these for v1, though one could argue if we had to launch without them, it would still be functional :)

**Comment by agclement** [comment]
> My knee-jerk reaction was that the private networks are the same. And maybe they are. Let's see...
> 
> VFN is public -> VFN -> validator
> PrivateFN is maybe something -> private -> public -> VFN -> validator
> or private -> VFN -> validator
> 
> So what do we gain if we have both of these as top level types? Maybe implicit upstream networks? But we already get that because validator is always upstream, so the VFN is kind of implicitly there already. Now with chains of pure private networks, we likely need to explicitly define upstream, sigh.
> 

I'd argue that all three full node networks  (2-4) are technically very similar and should build on the same underlying technical stack.  They are driven by specific operational use cases and differentiated primarily by higher level policies controlling (i) who interacts with them and  (ii) who operates them ==> which collectively imply a specific network it should hang off of.  

Networks in class (2) are used by *everybody*, operated by the association ==> attached to the core validator network.  This attachment is a logical necessity.  Further, the configurations for this network class likely must be a part of the on chain configuration to ensure that they are publicly discoverable.

Networks in class (3). are used by the public, operated by the public ==> attached to network class (2).   While these networks can in principal be attached to validator directly, doing so risks overwhelming the core validator  network.   It is unclear if these configurations belong on chain or not; I instinctively expect 'no' due to scale considerations, but there are load balancing concerns which likely require some centralised view...

Networks in class (4) are used by the the operator, operated by the operator ==> attached to the validator operated by the operator.  While these networks can in principal be attached to the  public full node ring, a savvy operator is likely to attach them to their validator directly.   These configurations do not belong on the chain/in a publicly visible location.


> Also not really optional, we need these for v1, though one could argue if we had to launch without them, it would still be functional :)

For a functional launch, are any full nodes needed ? ;)

In all seriousness, which full node use cases are needed?

**Comment by davidiw** [comment]
merging upstream
