### ISSUE TITLE
[validator-set] Remaining work

### ISSUE THREAD

**Issue by valerini** [libra/libra#4676]
## Work items
This issue tracks the remaining work items for move modules and accompanying code.
1) [x] Remove function `submit_reconfiguration_transaction` from `secure/key-manager/src/lib.rs` and move it to tests or elsewhere, as the key-manager code should only rely on the validator's private keys. Assignees: @valerini and @JoshLind
2) [x] Remove `encode_reconfigure_script`, `encode_set_validator_config_script` from `execution/executor/tests/storage_integration_test.rs` and possibly create a proper LibraMoveE2E testsuite in `libra/testsuite/libra_move_interface`. Assignees: @valerini 
4) [x] Clarify which accounts should hold permissions to call the following 5 methods: `LibraSystem::add_validator`, `LibraSystem::remove_validator`, `LibraSystem::update_and_reconfigure`, `LibraAccount::freeze`, `LibraAccount::unfreeze`  (for accounts with validator or validator operator roles). Assignees: @valerini, @dahliamalkhi 
3) [x] Distinguish between validator set change from other on-chain config update by a type-aware event and rename `reconfigure` to something like `set_validator_set` to make it clear and differentiate from other changes to on-chain config. Assignees: @zekun000, @valerini

## Motivation
This issue replaces the previous one: ([Issue 3161](https://github.com/libra/libra/issues/3161)).

**Comment by dahliamalkhi** [comment]
question: how can we freeze a validator operator only for a single, particular validator?

**Comment by davidiw** [comment]
> question: how can we freeze a validator operator only for a single, particular validator?

Curious, in what context, you would imagine this happening? In this implementation, removing the validator from the validator set would be the right operation.
