### ISSUE TITLE
[logging] Improve logging usability

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#5441]
### Pain points
- Log levels are inconsistent
- Fields inconsistent naming, get rid of “_0” “_1” fields, to just named
- Error logs don’t have enough context
- Logs don’t tell what is happening in the system as much as they could
- Kibana query language is hard to learn
- Can’t differentiate easily between Text & struct logs

#### Coding Usability
- [x] (https://github.com/libra/libra/issues/5442) Remove ability to auto convert logs to anonymous fields e.g. “_0” or “_1” 
- [x] (https://github.com/libra/libra/issues/5443) Make a differentiator between text and struct logs in the structured logs
- [x] maybe guidelines need to be updated (https://github.com/libra/libra/blob/master/documentation/coding_guidelines.md#logging)
- [ ] Work with a PE through an example section (e.g. Safety rules) for how we should log
- [ ] Guidelines for depth on error logs?
- [x] Once we have an example, distribute work between experts in each area to add appropriate logging

#### Viewing Usability
- [x] (https://github.com/libra/libra/pull/5476) Log levels for text logs
- [ ] (https://github.com/libra/libra/issues/5445) Kibana query language tutorial (we can even make it domain specific to our logs)
- [x] (https://github.com/libra/libra/issues/5565) Fix ordering issues of logs
- [x] Work through an example debugging exercise to see how hard it is (Already scheduled between Philip, Avery, and me)
- [x] (https://github.com/libra/libra/issues/5569) Prevent repeated logs

#### Reliability
- [x] Consider whether we should log something to file for structured logs

#### Feature Parity
- [ ] (https://github.com/libra/libra/issues/5570) Use Logstash in Cluster Test

**Comment by gregnazario** [comment]
All the important pieces have been completed
