### ISSUE TITLE
[logging] Ensure structured logs filter logs by log levels

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#5585]
### Overview
Currently, all logs made by text logging, are properly filtered, but all logs made by structured logging are not.  Ideally, we should be able to tune these accordingly such that we filter by log level.

### Tasks
- [x] (https://github.com/libra/libra/pull/5586) Filter by log level on writes
- [x] (https://github.com/libra/libra/pull/5586) Ensure log levels are canonical
- [x] (https://github.com/libra/libra/pull/5586) Make it easier to use log levels e.g. similar to the text `info!` and `error!` as `sl_info!` and `sl_error!`
- [x] Remove `crit!` from code base
- [x] Make followup items to distribute to each owner using the `send_struct_log!` to use the new macros

**Comment by gregnazario** [comment]
Followup items to owners
https://github.com/libra/libra/issues/5615
https://github.com/libra/libra/issues/5613
https://github.com/libra/libra/issues/5612

**Comment by gregnazario** [comment]
Remaining remove `crit!` from codebase

```
libra $ grep -r crit! . | sed 's/:.*$//g' | uniq -c | sort -nr
   8 ./language/libra-vm/src/errors.rs
   3 ./language/move-vm/runtime/src/loader.rs
   3 ./language/move-vm/runtime/src/interpreter.rs
   2 ./storage/libradb/src/pruner/mod.rs
   2 ./mempool/src/shared_mempool/coordinator.rs
   1 ./storage/libradb/src/system_store/mod.rs
   1 ./language/libra-vm/src/data_cache.rs
   1 ./execution/executor/src/lib.rs
   1 ./common/crash-handler/src/lib.rs
```
