### ISSUE TITLE
[logging] Update key manager logs with leveled logs

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#5615]
### Overview
Let's migrate send_struct_log! to use leveled macros, and remove `crit!` logs

### Tasks
- [ ] Remove any reference to `.warning()` or `.critical()`
- [ ] Change `send_struct_log!` to `sl_info!`, `sl_error!`, etc... accordingly similar to the text log macros
- [ ] replace any `crit!` with `error!`

**Comment by gregnazario** [comment]
@JoshLind :) if you could take some time to appropriately fix these logs, that would be great!

I'm tracking all of these in the logging project, to ensure I know how things are working out.

**Comment by JoshLind** [comment]
Sounds good, @gregnazario! I'll schedule some time to do them this week!

**Comment by gregnazario** [comment]
Resolved and tracked in a different way.
