### ISSUE TITLE
[logging] Enable Dynamic Log leveling

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#5716]
### Overview
During an operational event, it may be useful to lower the log level for a period of time to get additional logs.  This means we would want to change the log level, without restarting the node.

### Tasks
- [ ] Investigate how to make a debug call in to expose an `authenticated` way to change the log level
- [ ] Refactor logging to allow for changing the log level from the static variable it is now
- [ ] Test live in a cluster to ensure it can be changed on the fly

### Follow ups
- [ ] Should we allow for module granularity log leveling?
- [ ] Rate limit log level changes?

**Comment by bmwill** [comment]
Closed by https://github.com/libra/libra/pull/5930

**Comment by gregnazario** [comment]
Does this support changing the log level without restarting the process?

**Comment by bmwill** [comment]
Yes it does. See this commit message for for information https://github.com/libra/libra/pull/5930/commits/b270cb72e1df415a52fadee65c907e72e3ecefb1
