### ISSUE TITLE
Stable Testnet Faucet service

### ISSUE THREAD

**Issue by xli** [libra/libra#5943]
# 🚀 Feature Request

## Motivation

Existing Faucet service is problematic because of depending on starting a cli in child process for handling creating account and minting coins.
The cli itself is complicated for handling more interactive features and was built for people trying out Testnet. Hence the implementation is not optimized for running as a service.

## Pitch

1. New Testnet faucet service build in rust
2. Optimized for Testnet creating test accounts and minting coins.
3. Integrated with libra-swarm for manual test

## TODO

- [x] Replicate existing Faucet service interface and feature:
    - [x] Accepts auth key, amount and currency code for creating online testing account with coins transferred from a dd account.
        *  POST /?amount=25&auth_key=xxx&currency_code=XXX
        *  POST /mint?amount=25&auth_key=xxx&currency_code=XXX
    - [x] submit transactions and return new dd account sequence number
    - [x] validate request params, return meaningful error message for invalid param.
- [x] Integrate with libra logger, add simple bootstrap and request log.
- [x] Update libra-swarm to start with new faucet service for manual testing.
- [x] check account existence to decide whether submit creating account transaction
- [x] add optional param return_txn: bool, return submitted transaction bytes if it is true. Client can wait for transaction to know whether the transactions are succeed.
- [ ] add endpoint for creating DD account for testing.
- [ ] integration test in land build to confirm Faucet service working as expected for new PR
- [ ] handling parallel requests.
