### ISSUE TITLE
[observability] add metrics for throughput of metrics and logs

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#6196]
### Tasks
- [x] Add counter metric for # of metrics currently submitted (https://github.com/libra/libra/pull/6000)
- [x] Add counter metric for bytes of metrics currently submitted (https://github.com/libra/libra/pull/6000)
- [x] Add counter metric for # of logs currently submitted
- [x] Add counter metric for bytes of logs currently submitted (https://github.com/libra/libra/pull/6219)

**Comment by gregnazario** [comment]
This is a followup from @christinacelee 's post
