### ISSUE TITLE
[followup] Tracking SEV followup items

### ISSUE THREAD

**Issue by sherry-x** [libra/libra#9351]
- [ ] - We need to follow our release process, create release tags properly to make it easy for the community to follow - @sausagee to add this in the runbook
- [ ] - Implement subscription method for the community to followup with the updates. (RSS feed, website updates, mailing list) @9atatimer 
- [ ] - Create runbooks on how to use db-tool to pull partial data, how to replay specific range of transactions on the local db etc. @msmouse 
- [ ] - enable DEBUG log didn't give us extra information on the issue, are we logging the right things? @tzakian 
- [ ] - health-check tooling would be helpful in this case. https://github.com/diem/diem/issues/9352
